# Generated by Django 5.1.4 on 2025-01-06 08:29


import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the payment.",
                        max_length=7,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                        db_index=True,
                        default="PAYMENT",
                        help_text="Type of payment (regular payment or fine).",
                        max_length=7,
                    ),
                ),
                (
                    "session_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for the payment session.",
                        max_length=511,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier of the payment session.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "money_to_pay",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to be paid.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of payment creation."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last payment update."
                    ),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        help_text="The borrowing this payment is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
